import React, { useState, useEffect, useMemo, useRef } from 'react';
import { 
  Search, 
  Filter, 
  X, 
  ChevronDown, 
  ChevronUp, 
  Star, 
  DollarSign,
  Tag,
  Layers,
  SlidersHorizontal,
  Check
} from 'lucide-react';

interface FilterOption {
  label: string;
  value: string;
  count?: number;
  selected?: boolean;
}

interface PriceRange {
  min: number;
  max: number;
}

interface SearchFilters {
  query: string;
  categories: string[];
  priceRange: PriceRange;
  rating: number;
  tags: string[];
  inStock: boolean;
  onSale: boolean;
  sortBy: string;
  sortOrder: 'asc' | 'desc';
}

interface FacetedSearchProps {
  products: any[];
  onFiltersChange: (filters: SearchFilters) => void;
  initialFilters?: Partial<SearchFilters>;
  categories?: FilterOption[];
  tags?: FilterOption[];
  priceRange?: PriceRange;
  showAdvanced?: boolean;
  layout?: 'sidebar' | 'horizontal';
  className?: string;
}

const FacetedSearch: React.FC<FacetedSearchProps> = ({
  products,
  onFiltersChange,
  initialFilters = {},
  categories = [],
  tags = [],
  priceRange = { min: 0, max: 10000 },
  showAdvanced = true,
  layout = 'sidebar',
  className = ''
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState(initialFilters.query || '');
  const [selectedCategories, setSelectedCategories] = useState<string[]>(initialFilters.categories || []);
  const [selectedTags, setSelectedTags] = useState<string[]>(initialFilters.tags || []);
  const [currentPriceRange, setCurrentPriceRange] = useState<PriceRange>(
    initialFilters.priceRange || priceRange
  );
  const [minRating, setMinRating] = useState(initialFilters.rating || 0);
  const [inStockOnly, setInStockOnly] = useState(initialFilters.inStock || false);
  const [onSaleOnly, setOnSaleOnly] = useState(initialFilters.onSale || false);
  const [sortBy, setSortBy] = useState(initialFilters.sortBy || 'relevance');
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>(initialFilters.sortOrder || 'desc');
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set(['categories', 'price']));
  
  const searchInputRef = useRef<HTMLInputElement>(null);

  // Debounce search query
  useEffect(() => {
    const timer = setTimeout(() => {
      handleFiltersChange();
    }, 300);

    return () => clearTimeout(timer);
  }, [searchQuery]);

  // Update filters when any filter changes
  useEffect(() => {
    handleFiltersChange();
  }, [
    selectedCategories,
    selectedTags,
    currentPriceRange,
    minRating,
    inStockOnly,
    onSaleOnly,
    sortBy,
    sortOrder
  ]);

  // Auto-generate filter options from products
  const autoGeneratedFilters = useMemo(() => {
    const categoryMap = new Map<string, number>();
    const tagMap = new Map<string, number>();
    let maxPrice = 0;

    products.forEach(product => {
      // Categories
      if (product.category) {
        const count = categoryMap.get(product.category) || 0;
        categoryMap.set(product.category, count + 1);
      }

      // Tags
      if (product.tags && Array.isArray(product.tags)) {
        product.tags.forEach((tag: string) => {
          const count = tagMap.get(tag) || 0;
          tagMap.set(tag, count + 1);
        });
      }

      // Price range
      if (product.price > maxPrice) {
        maxPrice = product.price;
      }
    });

    return {
      categories: Array.from(categoryMap.entries()).map(([value, count]) => ({
        label: value.charAt(0).toUpperCase() + value.slice(1),
        value,
        count
      })),
      tags: Array.from(tagMap.entries()).map(([value, count]) => ({
        label: value.charAt(0).toUpperCase() + value.slice(1),
        value,
        count
      })),
      maxPrice: Math.ceil(maxPrice / 100) * 100 // Round up to nearest 100
    };
  }, [products]);

  const handleFiltersChange = () => {
    const filters: SearchFilters = {
      query: searchQuery,
      categories: selectedCategories,
      priceRange: currentPriceRange,
      rating: minRating,
      tags: selectedTags,
      inStock: inStockOnly,
      onSale: onSaleOnly,
      sortBy,
      sortOrder
    };

    onFiltersChange(filters);
  };

  const clearAllFilters = () => {
    setSearchQuery('');
    setSelectedCategories([]);
    setSelectedTags([]);
    setCurrentPriceRange(priceRange);
    setMinRating(0);
    setInStockOnly(false);
    setOnSaleOnly(false);
    setSortBy('relevance');
    setSortOrder('desc');
  };

  const getActiveFilterCount = () => {
    let count = 0;
    if (searchQuery) count++;
    if (selectedCategories.length > 0) count++;
    if (selectedTags.length > 0) count++;
    if (currentPriceRange.min > priceRange.min || currentPriceRange.max < (autoGeneratedFilters.maxPrice || priceRange.max)) count++;
    if (minRating > 0) count++;
    if (inStockOnly) count++;
    if (onSaleOnly) count++;
    return count;
  };

  const toggleSection = (section: string) => {
    const newExpanded = new Set(expandedSections);
    if (newExpanded.has(section)) {
      newExpanded.delete(section);
    } else {
      newExpanded.add(section);
    }
    setExpandedSections(newExpanded);
  };

  const renderStars = (rating: number, interactive = true, size = 'w-4 h-4') => {
    return Array.from({ length: 5 }, (_, i) => (
      <Star
        key={i}
        className={`${size} ${
          i < rating ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300'
        } ${interactive ? 'cursor-pointer hover:text-yellow-400' : ''}`}
        onClick={interactive ? () => setMinRating(i + 1) : undefined}
      />
    ));
  };

  const sortOptions = [
    { value: 'relevance', label: 'Relevance' },
    { value: 'price', label: 'Price' },
    { value: 'rating', label: 'Rating' },
    { value: 'name', label: 'Name' },
    { value: 'newest', label: 'Newest' },
    { value: 'bestseller', label: 'Best Selling' }
  ];

  // Sidebar layout
  if (layout === 'sidebar') {
    return (
      <div className={`w-80 bg-white border-r border-gray-200 h-full overflow-y-auto ${className}`}>
        {/* Header */}
        <div className="p-4 border-b border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold">Filters</h3>
            {getActiveFilterCount() > 0 && (
              <button
                onClick={clearAllFilters}
                className="text-sm text-blue-600 hover:text-blue-800"
              >
                Clear All ({getActiveFilterCount()})
              </button>
            )}
          </div>

          {/* Search Input */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              ref={searchInputRef}
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search products..."
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
        </div>

        {/* Filters */}
        <div className="p-4 space-y-6">
          {/* Sort */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Sort By</label>
            <div className="flex gap-2">
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500"
              >
                {sortOptions.map(option => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
              <button
                onClick={() => setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')}
                className="px-3 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
                title={`Sort ${sortOrder === 'asc' ? 'Descending' : 'Ascending'}`}
              >
                {sortOrder === 'asc' ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* Categories */}
          {(categories.length > 0 || autoGeneratedFilters.categories.length > 0) && (
            <div>
              <button
                onClick={() => toggleSection('categories')}
                className="flex items-center justify-between w-full text-sm font-medium text-gray-700 mb-2"
              >
                <span>Categories</span>
                {expandedSections.has('categories') ? 
                  <ChevronUp className="w-4 h-4" /> : 
                  <ChevronDown className="w-4 h-4" />
                }
              </button>
              
              {expandedSections.has('categories') && (
                <div className="space-y-2 max-h-48 overflow-y-auto">
                  {(categories.length > 0 ? categories : autoGeneratedFilters.categories).map(category => (
                    <label key={category.value} className="flex items-center space-x-2 text-sm">
                      <input
                        type="checkbox"
                        checked={selectedCategories.includes(category.value)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedCategories([...selectedCategories, category.value]);
                          } else {
                            setSelectedCategories(selectedCategories.filter(c => c !== category.value));
                          }
                        }}
                        className="rounded text-blue-600 focus:ring-blue-500"
                      />
                      <span className="flex-1">{category.label}</span>
                      {category.count && (
                        <span className="text-gray-400 text-xs">({category.count})</span>
                      )}
                    </label>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Price Range */}
          <div>
            <button
              onClick={() => toggleSection('price')}
              className="flex items-center justify-between w-full text-sm font-medium text-gray-700 mb-2"
            >
              <span>Price Range</span>
              {expandedSections.has('price') ? 
                <ChevronUp className="w-4 h-4" /> : 
                <ChevronDown className="w-4 h-4" />
              }
            </button>
            
            {expandedSections.has('price') && (
              <div className="space-y-3">
                <div className="flex items-center space-x-2">
                  <input
                    type="number"
                    placeholder="Min"
                    value={currentPriceRange.min}
                    onChange={(e) => setCurrentPriceRange({
                      ...currentPriceRange,
                      min: parseInt(e.target.value) || 0
                    })}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                  />
                  <span className="text-gray-500">-</span>
                  <input
                    type="number"
                    placeholder="Max"
                    value={currentPriceRange.max}
                    onChange={(e) => setCurrentPriceRange({
                      ...currentPriceRange,
                      max: parseInt(e.target.value) || autoGeneratedFilters.maxPrice || 10000
                    })}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
                  />
                </div>
                
                {/* Price range slider */}
                <div className="px-2">
                  <input
                    type="range"
                    min={priceRange.min}
                    max={autoGeneratedFilters.maxPrice || priceRange.max}
                    value={currentPriceRange.max}
                    onChange={(e) => setCurrentPriceRange({
                      ...currentPriceRange,
                      max: parseInt(e.target.value)
                    })}
                    className="w-full"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Rating */}
          <div>
            <button
              onClick={() => toggleSection('rating')}
              className="flex items-center justify-between w-full text-sm font-medium text-gray-700 mb-2"
            >
              <span>Minimum Rating</span>
              {expandedSections.has('rating') ? 
                <ChevronUp className="w-4 h-4" /> : 
                <ChevronDown className="w-4 h-4" />
              }
            </button>
            
            {expandedSections.has('rating') && (
              <div className="space-y-2">
                {[4, 3, 2, 1].map(rating => (
                  <button
                    key={rating}
                    onClick={() => setMinRating(minRating === rating ? 0 : rating)}
                    className={`flex items-center space-x-2 p-2 w-full text-left rounded-lg transition-colors ${
                      minRating === rating ? 'bg-blue-50 border-blue-200' : 'hover:bg-gray-50'
                    }`}
                  >
                    <div className="flex">
                      {renderStars(rating, false)}
                    </div>
                    <span className="text-sm">& up</span>
                    {minRating === rating && <Check className="w-4 h-4 text-blue-600 ml-auto" />}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Tags */}
          {(tags.length > 0 || autoGeneratedFilters.tags.length > 0) && (
            <div>
              <button
                onClick={() => toggleSection('tags')}
                className="flex items-center justify-between w-full text-sm font-medium text-gray-700 mb-2"
              >
                <span>Tags</span>
                {expandedSections.has('tags') ? 
                  <ChevronUp className="w-4 h-4" /> : 
                  <ChevronDown className="w-4 h-4" />
                }
              </button>
              
              {expandedSections.has('tags') && (
                <div className="space-y-2 max-h-48 overflow-y-auto">
                  {(tags.length > 0 ? tags : autoGeneratedFilters.tags).map(tag => (
                    <label key={tag.value} className="flex items-center space-x-2 text-sm">
                      <input
                        type="checkbox"
                        checked={selectedTags.includes(tag.value)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedTags([...selectedTags, tag.value]);
                          } else {
                            setSelectedTags(selectedTags.filter(t => t !== tag.value));
                          }
                        }}
                        className="rounded text-blue-600 focus:ring-blue-500"
                      />
                      <span className="flex-1">{tag.label}</span>
                      {tag.count && (
                        <span className="text-gray-400 text-xs">({tag.count})</span>
                      )}
                    </label>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Additional Filters */}
          {showAdvanced && (
            <div>
              <button
                onClick={() => toggleSection('advanced')}
                className="flex items-center justify-between w-full text-sm font-medium text-gray-700 mb-2"
              >
                <span>Additional Filters</span>
                {expandedSections.has('advanced') ? 
                  <ChevronUp className="w-4 h-4" /> : 
                  <ChevronDown className="w-4 h-4" />
                }
              </button>
              
              {expandedSections.has('advanced') && (
                <div className="space-y-3">
                  <label className="flex items-center space-x-2 text-sm">
                    <input
                      type="checkbox"
                      checked={inStockOnly}
                      onChange={(e) => setInStockOnly(e.target.checked)}
                      className="rounded text-blue-600 focus:ring-blue-500"
                    />
                    <span>In Stock Only</span>
                  </label>
                  
                  <label className="flex items-center space-x-2 text-sm">
                    <input
                      type="checkbox"
                      checked={onSaleOnly}
                      onChange={(e) => setOnSaleOnly(e.target.checked)}
                      className="rounded text-blue-600 focus:ring-blue-500"
                    />
                    <span>On Sale</span>
                  </label>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    );
  }

  // Horizontal layout (for mobile or compact view)
  return (
    <div className={`bg-white border border-gray-200 rounded-lg p-4 ${className}`}>
      {/* Mobile Filter Toggle */}
      <div className="flex items-center justify-between mb-4">
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="flex items-center space-x-2 text-sm font-medium text-gray-700 lg:hidden"
        >
          <SlidersHorizontal className="w-4 h-4" />
          <span>Filters</span>
          {getActiveFilterCount() > 0 && (
            <span className="bg-blue-600 text-white text-xs px-2 py-1 rounded-full">
              {getActiveFilterCount()}
            </span>
          )}
        </button>
        
        {/* Search for horizontal layout */}
        <div className="flex-1 max-w-md mx-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              ref={searchInputRef}
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search products..."
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
          </div>
        </div>
        
        {/* Sort dropdown for horizontal layout */}
        <div className="flex items-center space-x-2">
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            className="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500"
          >
            {sortOptions.map(option => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <button
            onClick={() => setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc')}
            className="p-2 border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            {sortOrder === 'asc' ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Expandable filters */}
      {(isOpen || window.innerWidth >= 1024) && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Categories */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Categories</label>
            <select
              multiple
              value={selectedCategories}
              onChange={(e) => {
                const values = Array.from(e.target.selectedOptions, option => option.value);
                setSelectedCategories(values);
              }}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              size={3}
            >
              {autoGeneratedFilters.categories.map(category => (
                <option key={category.value} value={category.value}>
                  {category.label} ({category.count})
                </option>
              ))}
            </select>
          </div>

          {/* Price Range */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Price Range</label>
            <div className="flex space-x-2">
              <input
                type="number"
                placeholder="Min"
                value={currentPriceRange.min}
                onChange={(e) => setCurrentPriceRange({
                  ...currentPriceRange,
                  min: parseInt(e.target.value) || 0
                })}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              />
              <input
                type="number"
                placeholder="Max"
                value={currentPriceRange.max}
                onChange={(e) => setCurrentPriceRange({
                  ...currentPriceRange,
                  max: parseInt(e.target.value) || 10000
                })}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              />
            </div>
          </div>

          {/* Rating */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Min Rating</label>
            <div className="flex items-center space-x-1">
              {renderStars(minRating)}
            </div>
          </div>

          {/* Additional Options */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Options</label>
            <div className="space-y-2">
              <label className="flex items-center space-x-2 text-sm">
                <input
                  type="checkbox"
                  checked={inStockOnly}
                  onChange={(e) => setInStockOnly(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span>In Stock</span>
              </label>
              <label className="flex items-center space-x-2 text-sm">
                <input
                  type="checkbox"
                  checked={onSaleOnly}
                  onChange={(e) => setOnSaleOnly(e.target.checked)}
                  className="rounded text-blue-600 focus:ring-blue-500"
                />
                <span>On Sale</span>
              </label>
            </div>
          </div>
        </div>
      )}

      {/* Active Filters Display */}
      {getActiveFilterCount() > 0 && (
        <div className="mt-4 flex items-center space-x-2 flex-wrap">
          <span className="text-sm text-gray-500">Active filters:</span>
          
          {searchQuery && (
            <span className="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
              Search: {searchQuery}
              <button
                onClick={() => setSearchQuery('')}
                className="ml-1 hover:text-blue-600"
              >
                <X className="w-3 h-3" />
              </button>
            </span>
          )}
          
          {selectedCategories.map(cat => (
            <span key={cat} className="inline-flex items-center px-2 py-1 bg-green-100 text-green-800 text-xs rounded-full">
              {cat}
              <button
                onClick={() => setSelectedCategories(selectedCategories.filter(c => c !== cat))}
                className="ml-1 hover:text-green-600"
              >
                <X className="w-3 h-3" />
              </button>
            </span>
          ))}
          
          {minRating > 0 && (
            <span className="inline-flex items-center px-2 py-1 bg-yellow-100 text-yellow-800 text-xs rounded-full">
              {minRating}+ stars
              <button
                onClick={() => setMinRating(0)}
                className="ml-1 hover:text-yellow-600"
              >
                <X className="w-3 h-3" />
              </button>
            </span>
          )}
          
          <button
            onClick={clearAllFilters}
            className="text-xs text-blue-600 hover:text-blue-800 underline"
          >
            Clear all
          </button>
        </div>
      )}
    </div>
  );
};

export default FacetedSearch;